function[str] = print_rv(rv)
str = strcat(num2str(rv.MEAN),',', ...
            num2str(rv.SDNN),',', ...
            num2str(rv.SDANN),',', ...
            num2str(rv.ASDNN),',', ...
            num2str(rv.TI),',', ...
            num2str(rv.AC),',', ...
            num2str(rv.DC) ...
        );